create table
  public.cart (
    id bigint generated by default as identity,
    catalog bigint null,
    quantity bigint null,
    constraint cart_pkey primary key (id),
    constraint cart_catalog_fkey foreign key (catalog) references catalog (id)
  ) tablespace pg_default;

  create table
  public.catalog (
    id bigint generated by default as identity,
    sku text not null,
    name text null,
    inventory integer null,
    price integer null,
    potion_type integer[] null,
    constraint catalog_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.global_inventory (
    id bigint generated by default as identity,
    num_red_ml integer null,
    gold integer null,
    num_green_ml integer not null default 0,
    num_blue_ml integer not null default 0,
    num_dark_ml integer not null default 0,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;