create table
  public.all_ml (
    id bigint generated by default as identity,
    name text null,
    constraint all_ml_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.cart (
    cart_id bigint generated by default as identity,
    customer text not null,
    constraint cart_pkey primary key (cart_id),
    constraint cart_customer_key unique (customer)
  ) tablespace pg_default;

create table
  public.catalog (
    id bigint generated by default as identity,
    sku text not null,
    name text null,
    inventory integer not null default 0,
    price integer not null default 50,
    potion_type integer[] null,
    priority integer null,
    constraint catalog_pkey primary key (id),
    constraint catalog_Priority_key unique (priority),
    constraint catalog_potion_type_key unique (potion_type)
  ) tablespace pg_default;

create table
  public.cart_items (
    id bigint generated by default as identity,
    cart_id bigint not null,
    catalog_id bigint null,
    quantity integer null,
    constraint cart_items_pkey primary key (id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references cart (cart_id),
    constraint cart_items_catalog_id_fkey foreign key (catalog_id) references catalog (id)
  ) tablespace pg_default;



create table
  public.global_inventory (
    id bigint generated by default as identity,
    num_red_ml integer null,
    gold integer null,
    num_green_ml integer not null default 0,
    num_blue_ml integer not null default 0,
    num_dark_ml integer not null default 0,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.gold_transactions (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    description text null,
    constraint gold_transactions_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.gold_ledger_entries (
    id bigint generated by default as identity,
    gold_transactions_id bigint null,
    change integer not null,
    constraint gold_ledger_entries_pkey primary key (id),
    constraint gold_ledger_entries_gold_transactions_id_fkey foreign key (gold_transactions_id) references gold_transactions (id)
  ) tablespace pg_default;

create table
  public.ml_transactions (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    description text null,
    constraint ml_transactions_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.ml_ledger_entries (
    id bigint generated by default as identity,
    ml_id bigint not null,
    ml_transactions_id bigint null,
    change integer null,
    constraint ml_ledger_entries_pkey primary key (id),
    constraint ml_ledger_entries_ml_id_fkey foreign key (ml_id) references all_ml (id),
    constraint ml_ledger_entries_ml_transactions_id_fkey foreign key (ml_transactions_id) references ml_ledger_entries (id)
  ) tablespace pg_default;




